### ISSUE TITLE
project cards improvements

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.com#14]
Right now, each project card in the Team and Projects sections only show a static image and a pretty bad placeholder title. They should:

* have good fallback behaviour for `bannerHasName: false` that looks good
* have on-hover interaction
* a simple modal on click to show the description and links (`links.repository`, `links.website`, etc.)

**Comment by bobheadxi** [comment]
/cc @cowjuh - I think @RachitMalik12 will be putting up some sketches for consideration! let us know if you have anything a bit more fleshed out as well

for reference, the original designs: https://www.figma.com/file/X67GE3ujjkpde4u6UGR3awpo/LP-Website-2019?node-id=1196%3A117&viewport=503%2C-1309%2C0.6188302636146545

**Comment by RachitMalik12** [comment]
Thanks @bobheadxi.. 
So disclaimer: not done much design work before but here is a hand drawn low fidelity sketch of what I think is a cool option. It is an early first draft and I am happy to keep iterating. 

I've taken inspiration from the old UBC launchpad website for the detailed part of the project shown at the bottom of the page and in the screenshot attached. I think it is pretty concise and the user can get a good understanding of what the project is about (That's how I found out about the projects when I was applying). So essentially as shown below when the banners are clicked a modal would pop up with a detailed view similar to what is in the last screenshot. I have placed an optional learn more button which can be removed but I put it there in case it is more clearer to some users. 

With regards to the bannerHasName: false I am not sure what the best option could be. One option is we could ensure that all projects have a title on their banner since this is under our control and I know our team and most of the teams have one. 
Otherwise they could be placed in the modal that pops up. 

We can also change the style of the 2nd screenshot to match the design system for the rest of the website. Let me know if you guys have any suggestions, particularly @cowjuh :). Thanks! 

![Project cards ](https://user-images.githubusercontent.com/16490844/79782473-cbf0b080-835c-11ea-9954-c5ddbb3008f3.jpg)

<img width="767" alt="Screen Shot 2020-04-20 at 11 15 33 PM" src="https://user-images.githubusercontent.com/16490844/79782514-df038080-835c-11ea-9bd0-a6f9794a3814.png">

**Comment by bobheadxi** [comment]
> With regards to the bannerHasName: false I am not sure what the best option could be. One option is we could ensure that all projects have a title on their banner since this is under our control and I know our team and most of the teams have one. Otherwise they could be placed in the modal that pops up.

It's hard enough to get teams to even put in information in the first place, so i think its still best to have a fallback - especially for older projects. Perhaps we could try some variations of:
* darken image and show text on hover
* show text with a drop shadow for clarity

---

Regarding the rest of the design: looks good! Some thoughts:

* hover can be accentuated using drop shadows or [`animate.css`](https://daneden.github.io/animate.css/) , or both! (depends on what looks like the right amount of "pop")
* a modal with a similar layout to the existing website sounds fine to me! we could add additional image options to the config for the expanded view as well. How are you planning to implement this? Note that [Bulma has a modal that might be a good starting point](https://bulma.io/documentation/components/modal/), though judging from the demos a bit of styling and maybe animation will need to be done ([`animate.css`](https://daneden.github.io/animate.css/) could come in handy here too!)

**Comment by bobheadxi** [comment]
With that in mind, feel free to start implementing this @RachitMalik12 and open up a WIP PR for us to check out when you're ready :D

**Comment by bobheadxi** [comment]
@RachitMalik12 you might want to take a look at the interactions @srijonsaha added in #42 for ideas on similar animations you can add to the project cards!

**Comment by RachitMalik12** [comment]
> With that in mind, feel free to start implementing this @RachitMalik12 and open up a WIP PR for us to check out when you're ready :D

Sounds good working on it now! Thanks @bobheadxi

**Comment by RachitMalik12** [comment]
> * Bulma has a modal that might be a good starting point
Yeah Bulma seems like a good starting point. Will probably have to add more css and animations but I'll start with that and see how it looks.

**Comment by RachitMalik12** [comment]
> > With regards to the bannerHasName: false I am not sure what the best option could be. One option is we could ensure that all projects have a title on their banner since this is under our control and I know our team and most of the teams have one. Otherwise they could be placed in the modal that pops up.
> 
> It's hard enough to get teams to even put in information in the first place, so i think its still best to have a fallback - especially for older projects. Perhaps we could try some variations of:
> 
> * darken image and show text on hover
> * show text with a drop shadow for clarity

I like the idea of darkening the image and showing the text on hover something similar to this: https://www.w3schools.com/howto/howto_css_image_overlay.asp ? Maybe not as extreme but instead of that blue background just blur.. 

> Regarding the rest of the design: looks good! Some thoughts:
> 
> * hover can be accentuated using drop shadows or [`animate.css`](https://daneden.github.io/animate.css/) , or both! (depends on what looks like the right amount of "pop")
> * a modal with a similar layout to the existing website sounds fine to me! we could add additional image options to the config for the expanded view as well. How are you planning to implement this? Note that [Bulma has a modal that might be a good starting point](https://bulma.io/documentation/components/modal/), though judging from the demos a bit of styling and maybe animation will need to be done ([`animate.css`](https://daneden.github.io/animate.css/) could come in handy here too!)

Yeah Bulma seems like a good starting point. Will probably have to add more css and animations but I'll start with that and see how it looks.

**Comment by bobheadxi** [comment]
> I like the idea of darkening the image and showing the text on hover something similar to this: https://www.w3schools.com/howto/howto_css_image_overlay.asp ? Maybe not as extreme but instead of that blue background just blur..

Sounds like a good start!
