### ISSUE TITLE
use an iconset

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.com#46]
Right now I'm exporting logos individually from figma/sourcing from online, but it might be more productive to leverage an existing website

the old one used [fontawesome](https://fontawesome.com/icons?d=gallery&m=free), which seemed to work fine

**Comment by bobheadxi** [comment]
@RachitMalik12 @srijonsaha any of y'all used a different iconset that might be better than fontawesome's

**Comment by RachitMalik12** [comment]
> @RachitMalik12 @srijonsaha any of y'all used a different iconset that might be better than fontawesome's

I think fontawesome is good!

**Comment by srijonsaha** [comment]
I like this one: https://antonreshetov.github.io/vue-unicons/. The icons look simple and clean.

**Comment by RachitMalik12** [comment]
I am not too picky with this stuff so open to anything but here is how font awesome looks on the modal..however with font awesome we just need to link to a cdn and the vue-unicorns is one additional npm package. Still both look great imo and not sure how much impact is one more npm package. I'll put up a quick PR once we have decide to make the switch to all icons and get rid of the svgs since I need it for my project card modal stuff.

<img width="723" alt="Screen Shot 2020-04-22 at 12 50 42 PM" src="https://user-images.githubusercontent.com/16490844/79952407-014de900-8498-11ea-8ed8-078d2241ce28.png">

**Comment by bobheadxi** [comment]
Wow the Vue unicons look amazing! It also has a CDN option, which imo makes this an obvious win over fontawesome:

```
<link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css">
```

https://iconscout.com/unicons/getting-started/line

That said, I don’t mind (and would personally prefer) the npm install option when it comes to icons

**Comment by RachitMalik12** [comment]
> Wow the Vue unicons look amazing! It also has a CDN option, which imo makes this an obvious win over fontawesome:
> 
> ```
> <link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css">
> ```
> 
> https://iconscout.com/unicons/getting-started/line
> 
> That said, I don’t mind (and would personally prefer) the npm install option when it comes to icons

https://github.com/antonreshetov/vue-unicons/issues/21 this has issues with typescript. @srijonsaha have you used it with typescript before? I'll use the cdn for now in the case we can't find a workaround..

**Comment by RachitMalik12** [comment]
https://github.com/antonreshetov/vue-unicons/issues/21 - there are issues with vue-unicons and typescript. There was a PR merged in the library to add type declarations and I tried using those but it lead to whole host of issues on trying to import the icons file. In order to not be blocked I'll use the cdn for now. 
Edit: I am having issues styling the icons now when using the cdn ugh :(
@srijonsaha have you used this with typescript before? any ideas?

**Comment by bobheadxi** [comment]
@RachitMalik12 @srijonsaha I've got the icon set working in https://github.com/ubclaunchpad/new/pull/80
