### ISSUE TITLE
replace markdown emoji in project descriptions

### ISSUE THREAD

**Issue by RachitMalik12** [ubclaunchpad/ubclaunchpad.com#64]
Emojis for: 
- Sync
- Inertia 
- Etch.space 
- Minutes 
don't show up on the description. 
Using emojis from github repos and old website.

**Comment by bobheadxi** [comment]
I implemented this in the old website here: https://github.com/ubclaunchpad/ubclaunchpad.github.io/pull/58

it should be pretty straight forward to do the same thing here

**Comment by RachitMalik12** [comment]
> I implemented this in the old website here: [ubclaunchpad/ubclaunchpad.github.io#58](https://github.com/ubclaunchpad/ubclaunchpad.github.io/pull/58)
> 
> it should be pretty straight forward to do the same thing here

oo this is interesting. We can go with the simpler one for now? or I am happy to give that a shot

**Comment by bobheadxi** [comment]
tbh easier to just make sure we use actual emoji for now - that implementation was only really because the old website used to pull users from the old Rocket, and render their descriptions. Since Slack tracks emoji as markdown `:emoji:`, that was the only way to have emoji work.

That said, it does remind me that it might be cool to bring back the old team view that would pull the actual slack profiles from Rocket... probably something for much further down the line 🙃

**Comment by bobheadxi** [comment]
since we're just replacing the content, imma relabel this

**Comment by RachitMalik12** [comment]
Makes sense.. Cool I'll merge it now :)
